### ISSUE TITLE
There is no password field for protected wirelesss networks in the configuration window

### ISSUE THREAD

**Issue by javier-lopez** [eurogiciel-oss/connman-json-client#13]
Hello,

This may be related to issue #12, when a protected network is not configured correctly there is no way to set the correct password within the configuration window.

The workaround is to restart the `connman` daemon (`sudo service connman restart`)

![rpfjzh0y](https://cloud.githubusercontent.com/assets/75626/6242464/caf71082-b6f4-11e4-89b1-de00bdee205d.png)
![kod6tbqt](https://cloud.githubusercontent.com/assets/75626/6242450/89db7188-b6f4-11e4-8ab7-d72d0dbdf924.png)

**Comment by alan-mushi** [comment]
No, you can't enter credentials in service configuration (it's not exposed), you need to use connman's agent to do this.
