### ISSUE TITLE
connman_curses doesn't remove out of range essids when refreshing the wireless network list

### ISSUE THREAD

**Issue by javier-lopez** [eurogiciel-oss/connman-json-client#7]
Hi,

`connman_curses` doesn't remove out of range essids when listing them.

**Testcase**
1. Disconnect from all wireless networks
2. Launch `connman_curses`
3. Select the `wifi technology`
   - Write down the APs available
4. Turn off a nearby AP
5. Press F6 (forcing a scan)
6. Press F5 (refreshing the network list)
   - The nearby turned off AP still appears in the list
7. Select the turned off nearby AP
   - An error is displayed
     `[ERROR] Unidentified call back: status: -1, jobj: { "ERROR": [ "Method \"Connect\" with signature \"\" on interface \"net.connman.Service\" doesn't exist\n" ] }`

**Expected behavior**

In my opinion, `connman-curses` should remove old APs who are not in range anymore.

Also, it seems that special characters aren't being escaped correctly in the above error message.

**Comment by alan-mushi** [comment]
Hi,

I concur and a pull request is ongoing. I'm double-checking the removal in the `services` json array (strangely enough, no function is made for this task in json-c).

> An error is displayed `[ERROR] Unidentified call back: status: -1, jobj: { "ERROR": [ "Method \"Connect\" with signature \"\" on interface \"net.connman.Service\" doesn't exist\n" ] }`

You  try to connect to the AP you turned off correct ?
The special characters are correctly escaped, this is coming straight from json-c which escape `"` in strings (other than object keys).

**Comment by javier-lopez** [comment]
Awesome,

Yep, I tried to connect to a turned off AP which still was part of the list. I tested the issue7 branch and it now removes the not available APs from the list.

Thanks =)!
